# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.0
epsilon_anneal_time: 200000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000
batch_size: 32  # Number of episodes to train on

# update the target network every {} episodes if >1, else soft update
target_update_interval_or_tau: 0.01

# ns: no parameter sharing
mac: "basic_mac"
agent: "rnn"

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
hidden_dim: 128
lr: 0.0003
standardise_rewards: True
agent_output_type: "q"
learner: "q_learner"
double_q: True
use_rnn: True      # rnn: use GRU
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix"

t_max: 4102000
save_model_interval: 500000
# 41 evaluations during training, each eval point runs 100 episodes
test_nepisode: 100
test_interval: 100000
log_interval: 100000